### ISSUE TITLE
RHEL 7 now includes copr support

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#113]
Simpler installation on RHEL 7 was pending copr support: https://github.com/mgm3746/garbagecat#rhel-7. Will garabgecat continue to have releases tagged so https://github.com/bostrt/rpm-garbagecat can be kept up-to-date?

**Comment by mgm3746** [comment]
Yes, sorry, I have neglected to do a release for some time. I just pushed one out and will try to do better with releases going forward.
