### ISSUE TITLE
Shenandoah GC Support

### ISSUE THREAD

**Issue by imptrck** [mgm3746/garbagecat#120]
Hi, 

I was trying the Shenandoah GC with Garbagecat but it's not recognizing the output yet.
I'll add the gc logs for this.

[shenandoah.tar.gz](https://github.com/mgm3746/garbagecat/files/2833126/shenandoah.tar.gz)

**Comment by mgm3746** [comment]
Hi, yes, please add the logs, and I will take a look.

**Comment by imptrck** [comment]
Added it to the first comment. Thanks \õ

**Comment by mgm3746** [comment]
Hi,

Sorry I missed the logging in your initial comment. 

Please attach:

1) Output from running "java -version".
2) The JVM options you used to start the JVM.

**Comment by imptrck** [comment]
No problem!

Here is it: 

-$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode, sharing)

- Flags used in JBoss EAP 7.2. (Added only -XX:+UserShenandoahGC to the default ones):
   JAVA_OPTS="-Xms1303m -Xmx1303m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true"
   JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true -XX:+UseShenandoahGC"

**Comment by mgm3746** [comment]
Sorry for the delay. The fix has been committed.
