### ISSUE TITLE
Unidentified log lines in JDK10 (application stop times)

### ISSUE THREAD

**Issue by Norbo11** [mgm3746/garbagecat#124]
In Java 10 you can run -Xlog:safepoint as a replacement for -XX:+PrintGCApplicationStoppedTime

garbagecat doesn't seem to support this:

```
[0.099s][info][safepoint    ] Total time for which application threads were stopped: 0.0001360 seconds, Stopping threads took: 0.0000837 seconds
[0.170s][info][safepoint    ] Application time: 0.0715079 seconds
```

**Comment by mgm3746** [comment]
Since JDK10 is not a production release, and this option is deprecated in JDK11, I wasn't planning to add support for this, but I will keep this open and circle back to it after completing JDK11 updates.

**Comment by mgm3746** [comment]
The goal of garbagecat is troubleshooting production and pre-production issues, so the focus is on Long Term Support releases (e.g. 8, 11, 17).
