### ISSUE TITLE
Unidentified log lines in JDK11

### ISSUE THREAD

**Issue by coco1001998** [mgm3746/garbagecat#127]
The below is GC log configuration:

-Xlog:gc*:file=$JBOSS_HOME/standalone/log/gc_%p_%t.log:time,uptimemillis:filecount=5,filesize=50M -XX:+UseG1GC

[gc_104_2019-05-09_01-38-55.log](https://github.com/mgm3746/garbagecat/files/3164725/gc_104_2019-05-09_01-38-55.log)
[report.txt](https://github.com/mgm3746/garbagecat/files/3164726/report.txt)

**Comment by ptyagii** [comment]
@mgm3746 The default gc is G1 in JDK 11 as the output of command "java -XX:+PrintFlagsFinal -version" shows: 
`    bool UseG1GC                                  = true                                      {product} {ergonomic}`
The format for G1 logging in JDK 11 has changed a bit. I found it easier to read the log file though. 
However, garbagecat is not able to identify the log lines and it does not generate the report properly with the summary and analysis.

**Comment by mgm3746** [comment]
Fixed in latest build.
