### ISSUE TITLE
UNIDENTIFIED LOG LINE(S) with G1 and JDK1.7

### ISSUE THREAD

**Issue by juliancervino** [mgm3746/garbagecat#135]
Hi there!!

I have some unindentified log lines, using G1 and JDK1.7. 

JVM_LOG_OPTIONS:
```
	-verbose:gc \
	-XX:+PrintGCDateStamps \
	-XX:+PrintGCDetails \
	-XX:+PrintAdaptiveSizePolicy \
	-XX:+PrintGCApplicationStoppedTime
	-XX:+PrintGCApplicationConcurrentTime
	-XX:-PrintCommandLineFlags
```

The "offending" lines are like these:

> 2020-04-29T22:05:39.708+0200: 1745.417: [GC cleanup 1745.419: [G1Ergonomics (Concurrent Cycles) finish cleanup, occupancy: 22498457048 bytes, capacity: 32212254720 bytes, known garbage: 9291782792 bytes (28.85 %)]21456M->20543M(30720M), 0.0155840 secs] [Times: user=0.07 sys=0.06, real=0.01 secs]
> 2020-04-29T22:07:25.554+0200: 1851.263: [GC cleanup 1851.264: [G1Ergonomics (Concurrent Cycles) finish cleanup, occupancy: 22016745768 bytes, capacity: 32212254720 bytes, known garbage: 2199235288 bytes (6.83 %)]20996M->20978M(30720M), 0.0125730 secs] [Times: user=0.06 sys=0.05, real=0.01 secs]
> 2020-04-29T22:07:52.739+0200: 1878.448: [GC cleanup 1878.449: [G1Ergonomics (Concurrent Cycles) finish cleanup, occupancy: 28384839096 bytes, capacity: 32212254720 bytes, known garbage: 11510668096 bytes (35.73 %)]27069M->24733M(30720M), 0.0119250 secs] [Times: user=0.06 sys=0.04, real=0.01 secs]
> 2020-04-29T22:08:14.984+0200: 1900.693: [GC cleanup 1900.694: [G1Ergonomics (Concurrent Cycles) finish cleanup, occupancy: 28057009752 bytes, capacity: 33453768704 bytes, known garbage: 10570093832 bytes (31.60 %)]26757M->20180M(31904M), 0.0082590 secs] [Times: user=0.05 sys=0.03, real=0.01 secs]
> 2020-04-29T22:09:54.683+0200: 2000.392: [GC cleanup 2000.393: [G1Ergonomics (Concurrent Cycles) finish cleanup, occupancy: 22807553184 bytes, capacity: 33453768704 bytes, known garbage: 2176162424 bytes (6.50 %)]21750M->21668M(31904M), 0.0106580 secs] [Times: user=0.08 sys=0.03, real=0.01 secs]

Thanks!!

**Comment by juliancervino** [comment]
Hi, again.

I have read (now) the guidelines to create an issue related to unidentified log lines, so I'm attaching the full gc log.

And this is the command I'm using (just in case):

> java -jar garbagecat-3.0.3.jar -p -o prd-solr-c03-0001-50.report prd-solr-c03-0001.gc

Thanks

[prd-solr-c03-0001.zip](https://github.com/mgm3746/garbagecat/files/4557532/prd-solr-c03-0001.zip)

**Comment by mgm3746** [comment]
Thank you! I will take a look now.

**Comment by mgm3746** [comment]
Thank you for reporting this. It should be fixed now in the latest commit.

**Comment by juliancervino** [comment]
Thanks to you for your hard work!!
