### ISSUE TITLE
Timestamp problem (timezone?/dst?)

### ISSUE THREAD

**Issue by pfichtner** [mgm3746/garbagecat#147]
Since I started with garbagecat there is always one failing test: TestShenandoahDegeneratedGcEvent#testLogLineMetaspace
It fails with "Time stamp not parsed correctly. ==> expected: <657035501386> but was: <657039101386>" which is a difference of one hour. What value should the timestamp have? Millis since 2000-01-01 local timezone? Millis since 2000-01-01 UTC? Why 2000 and not 1970? 
I tried to fix the issue which is not very nice using Java 6 (the timezone of the log line currently is ignored). Is there any good reason why this project still is based on Java 6 with an EOL in 2013?

**Comment by mgm3746** [comment]
> Is there any good reason why this project still is based on Java 6 with an EOL in 2013?

No good reason. I updated the source/target in the pom just now to 1.8.

**Comment by mgm3746** [comment]
>What value should the timestamp have? Millis since 2000-01-01 local timezone? Millis since 2000-01-01 UTC? Why 2000 and not 1970?

It's the number of milliseconds after the JVM starts. 

To support unified logging that just has a datestamp (e.g. 2020-08-18T14:05:42.515+0000: [Pause Degenerated GC (Mark) 93058M->29873M(98304M), 1285.045 ms]), I calculate the timestamp as the difference between the gc datestamp and 2000-01-01 UTC. It's arbitrary, any fixed date/time could be used. Just some value is needed to compute throughput.

**Comment by pfichtner** [comment]
Since the timezone is ignored (+0000) the difference to the timestamp in UTC depends on the timezone the computer the code is executed on. That's the reason why the testcase fails on my machine. 
I suggest to take care of timezones used in ISO timestamps. It's unlikely that timezone will differ on log entries but the  information given should be taken into account.

**Comment by mgm3746** [comment]
Ok, I added timezone to GcUtil.getDate() just to stub it in. I'm not sure about the implementation, so feel free to implement it there, or revise in whatever way you think is best.

**Comment by mgm3746** [comment]
I believe all tests are now timezone independent. Please pull the latest and let me know if any tests fail for you.

**Comment by pfichtner** [comment]
One test was/is not: https://github.com/mgm3746/garbagecat/blob/2f0a659b5dcf1c4898f67370f643068db2bbfe87/src/test/java/org/eclipselabs/garbagecat/util/TestGcUtil.java#L150
The expected time depends on the computers timezone (because no timezone is specified). I suggest to solve it by comparing the offset to 1970-01-01 UTC (via getTime's long value)
```
@Test
void testConvertDateStampStringToDate() {
   Date date = GcUtil.parseDateStamp("2010-02-26T09:32:12.486-0600");
-        assertEquals(parseDate("2010-02-26", "10:32:12.486"), date);
+        assertEquals(1267198332486L, date.getTime());
}

You can apply the diff by accepting PR #149

```

**Comment by mgm3746** [comment]
Great, thank you!
