### ISSUE TITLE
Max heap values not calculating

### ISSUE THREAD

**Issue by mgm3746** [mgm3746/garbagecat#155]
When parsing logging that only has combined data, getting 0 max heap values:

Max Heap Occupancy: 0K
Max Heap After GC: 0K
Max Heap Space: 0K

**Comment by mgm3746** [comment]
Added TestJvmRun.testSummaryStatsShenandoah() (commented out) to verify future fix.

**Comment by mgm3746** [comment]
@pfichtner I see I did not have a test for this, so I added one, commented out for now. I will take a look, but it may be a easy one for you, whereas I'm still getting up to speed on the Streams.

**Comment by mgm3746** [comment]
@pfichtner feel free to suggest a better fix.

**Comment by pfichtner** [comment]
I'll keep an eye on it

**Comment by pfichtner** [comment]
After checkout one test fails
```
[ERROR] Failures: 
[ERROR]   TestShenandoahFullGcEvent.testParseLogLineUnifiedTime:132 Time stamp not parsed correctly. ==> expected: <635008911130> but was: <635030511130>
```
Unified#convertDatestampToMillis calculates the difference of two dates: The JVM's start that with local timezone and the passed one which defines a timezone. So the difference will depend on the timezone the test gets executed in.

**Comment by pfichtner** [comment]
Problem can be fixed by setting a timezone. 
UnifiedUtil: 
`private static final Date jvmStartDate = GcUtil.parseDateStamp("2000-01-01T00:00:00.000-0500");`

If you'd prefer to use UTC you would have to adjust one expected long value in the JUnit test
