### ISSUE TITLE
Unidentified log line(s)

### ISSUE THREAD

**Issue by allthebits** [mgm3746/garbagecat#157]
[report.txt](https://github.com/mgm3746/garbagecat/files/6331585/report.txt)

Please submit an issue so we can investigate: https://github.com/mgm3746/garbagecat/issues.

**Comment by mgm3746** [comment]
Hi, 

Could you please attach the raw gc log? Or at least a subset of it that includes some of the logging lines that are not being parsed.

**Comment by allthebits** [comment]
Can you confirm that the data in the file:  report.txt is not what you need?  If not I will upload the GC log file.

**Comment by mgm3746** [comment]
I need the raw gc log or a subset of it that includes the unidentified logging lines.

**Comment by allthebits** [comment]
[gc_grn1p-ctx64-pub01_jdk8_2021-04-09.zip](https://github.com/mgm3746/garbagecat/files/6343132/gc_grn1p-ctx64-pub01_jdk8_2021-04-09.zip)

**Comment by mgm3746** [comment]
I'm sorry for the delay. I have added initial support for -XX:+PrintAdaptiveSizePolicy output in ba4d589ab0452739a23c92ea382573c64bc952e4. It's likely there will be other patterns, so please report any other logging related to -XX:+PrintAdaptiveSizePolicy output.
