### ISSUE TITLE
Change safepoint precision to nanoseconds

### ISSUE THREAD

**Issue by mgm3746** [mgm3746/garbagecat#163]
Align with JDK17

**Comment by mgm3746** [comment]
Hi, @mjtrangoni I will look at doing this today.

**Comment by mgm3746** [comment]
Please pull the latest and test and let me know if you have any feedback.

**Comment by mjtrangoni** [comment]
I will check it tomorrow, don't know why I didn't receive any notification from GitHub last weeks!
