### ISSUE TITLE
Provide a docker image

### ISSUE THREAD

**Issue by mjtrangoni** [mgm3746/garbagecat#165]
Hi,

first of all, thank you for this project!
I was asking me why not providing a ready-to-use docker image here, so we can skip the whole installation of RPMs.

Thank you!

**Comment by mgm3746** [comment]
Yes, that sounds good. I don't know how to go about that. I guess there are maven plugins to build a docker image?

**Comment by mjtrangoni** [comment]
@mgm3746 indeed, I would go a multi-stage build, so you build the app in a maven image, like [this](docker.io/library/maven:3.8.5-openjdk-17-slim), and then you use it that build in something like [this](docker.io/library/openjdk:17-jdk-slim).

**Comment by mgm3746** [comment]
@mjtrangoni Can you provide detailed steps? I don't know much about containers or container builds, so someone would have to provide details what to do.
