### ISSUE TITLE
org.eclipselabs.garbagecat.domain.TimeWarpException: Logging reversed

### ISSUE THREAD

**Issue by arshad-aziz** [mgm3746/garbagecat#181]
I was using the latest version (4.0.1) of garbagecat and came across the below exception.
~~~
Exception in thread "main" org.eclipselabs.garbagecat.domain.TimeWarpException: Logging reversed: 
201887.553: [GC (Allocation Failure) [PSYoungGen: 1371712K->18361K(1375232K)] 1536889K->185042K(4171776K), 0.0505441 secs] [Times: user=0.10 sys=0.00, real=0.05 secs] 
114733.445: [GC (Allocation Failure) [PSYoungGen: 1363878K->19243K(1370624K)] 1511643K->167875K(4167168K), 0.0486211 secs] [Times: user=0.10 sys=0.00, real=0.04 secs] 
	at org.eclipselabs.garbagecat.service.GcManager.store(GcManager.java:868)
	at org.eclipselabs.garbagecat.Main.createReport(Main.java:140)
	at org.eclipselabs.garbagecat.Main.main(Main.java:672)
~~~

I encountered this in an earlier version (3.0.6) as well.

**Comment by mgm3746** [comment]
Hi,

garbage is reporting that the order of the logging does not make any sense (114733.445 should have come before 201887.553, not after).

I cannot think of a valid use case where this would happen, so I think either there is logging from multiple JVMs/runs mixed together in the log file, or somehow the logging is out of order. 

There is the "-r" option that will sort/reorder the logging. This can fix some simple issues that I have seen related to extracting logging from a central repository (e.g. splunk). 

However, if the logging is really mixed up, it would have to be fixed outside of garbagecat.
