### ISSUE TITLE
Create latest tag in container image repo

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#183]
```
$ podman pull ghcr.io/mgm3746/garbagecat
Trying to pull ghcr.io/mgm3746/garbagecat:latest...
Error: initializing source docker://ghcr.io/mgm3746/garbagecat:latest: reading manifest latest in ghcr.io/mgm3746/garbagecat: manifest unknown
```

Trying to pull an image (excluding the tag) defaults to latest. Can a `latest` tag be used since docker and podman both default to that?

**Comment by mgm3746** [comment]
Hi Robert,

I believe I have fixed it w/ this addition:
https://github.com/mgm3746/garbagecat/commit/7e06efab4cdecae916c1402ec966837dfa0756a5

Please test and let me know if it's working as expected now.
