### ISSUE TITLE
Base on jdk build time to suggest updrage jdk

### ISSUE THREAD

**Issue by cyberdak** [mgm3746/garbagecat#187]
I just look at my  gclog , found it use jdk8u66 and it's build in 2015 ,event 8 years early.

mostly user can't awake to their jdk is so old.

Mybay can suggest user updrage to a lastest jdk version.

8u66 -> 8u362 .
11.0.2 -> 11.0.18 .

**Comment by mgm3746** [comment]
I added analysis to check if the build > 365 days old. If it is, the following analysis will be displayed:
*The JDK is very old (2704 days).

I don't know that it's appropriate to suggest an upgrade, as many customers run old JDKs and cannot upgrade them without a full test cycle, so I kept the analysis generic and info level.

Let me know if this is acceptable for your.
