### ISSUE TITLE
G1 remark event UNIDENTIFIED

### ISSUE THREAD

**Issue by cyberdak** [mgm3746/garbagecat#188]
[check-206.log](https://github.com/mgm3746/garbagecat/files/10979549/check-206.log)

this log has many remark event.

but can't found remark in Event typs : 
```
=======================================================================
SUMMARY:
-----------------------------------------------------------------------
Datestamp First: 2023-03-15T16:17:06.083+0800
Timestamp First: 160496.234 secs
Datestamp Last: 2023-03-15T19:46:28.398+0800
Timestamp Last: 173058.548 secs
# GC Events: 695
Event Types: G1_YOUNG_INITIAL_MARK, TENURING_DISTRIBUTION, G1_CONCURRENT, G1_CLEANUP
Heap Used Max: 2198528K
Heap After GC Max: 1720320K
Heap Allocation Max: 4194304K
GC Throughput: ~100%
GC Pause Max: 0.008 secs
GC Pause Total: 0.056 secs
```

I think gc_pause_max & gc_pause_total maybe are both incorrect because the result did't contains G1 remark

**Comment by mgm3746** [comment]
Are you using the latest container build? 

I get the following with the latest container build:
=======================================================================
SUMMARY:
-----------------------------------------------------------------------
Datestamp First: 2023-03-15T16:17:06.083+0800
Timestamp First: 160496.234 secs
Datestamp Last: 2023-03-15T19:46:28.398+0800
Timestamp Last: 173058.548 secs
# GC Events: 722
Event Types: TENURING_DISTRIBUTION, G1_YOUNG_PAUSE, G1_YOUNG_INITIAL_MARK, G1_CONCURRENT, G1_REMARK, G1_CLEANUP, G1_MIXED_PAUSE
# Parallel Events: 722
Heap Used Max: 3820544K
Heap After GC Max: 1836032K
Heap Allocation Max: 4194304K
GC Throughput: ~100%
Allocation Rate: 98 MB/sec
GC Pause Max: 0.132 secs
|--Ext Root Scanning: 0.020 secs
GC Pause Total: 46.220 secs
|--Ext Root Scanning: 3.788 secs
Other Max: 0.027 secs
Other Total: 5.692 secs
=======================================================================

**Comment by cyberdak** [comment]
Looks like because i did't add "-p" option manually.
If check UNIDENTIFIED log , retry analyze with "-p" auto?

**Comment by mgm3746** [comment]
> If check UNIDENTIFIED log , retry analyze with "-p" auto?

Yes, that's right. If there are unidentified lines when you run without the "-p" preparsing option, you should see this error level message:
"Unidentified log line(s). Try running with the -p (preparsing) option."
