### ISSUE TITLE
HeapDumpPath advisory

### ISSUE THREAD

**Issue by Sarkie** [mgm3746/garbagecat#195]
Our variable is set as
```-XX:HeapDumpPath=/u01/oracle/heapdumps/```
But still this appears in the report
```*A heap dump file name has been specified with the -XX:HeapDumpPath (e.g. -XX:HeapDumpPath=/mydir/heapdump.hprof). Generally you only want to specify a directory (e.g. -XX:HeapDumpPath=/mydir/) and let the JVM use the default file name, which includes the process id. If you specify a file name, heap dumps will not overwrite each other. Only the initial file will be written. Subsequent heap dumps will fail due to the existing file. Unless disk space is a concern, you typically do not want to lose data. Reference: https://access.redhat.com/solutions/21109```

Rather not upload the report but can if needed.

Thanks!

**Comment by mgm3746** [comment]
Hi, thank you for reporting this. This should be fixed now in the latest release. Please test and confirm. If you are still hitting this, there must be something more going on, so please zip up and attach the raw gc logging (with any identifiable information removed/sanitized).
