### ISSUE TITLE
Numerous unidientifed log lines

### ISSUE THREAD

**Issue by tjherring** [mgm3746/garbagecat#196]
Receive a lot of Unidentified log lines warnings.  Not sure that it matter for the analysis, but wondering if it does?  We ran garbage cat with the '-p' option.

We are running the binary jar from this site.  version 4.0.1.  The application that is logging is running:
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment Temurin-11.0.20+8 (build 11.0.20+8)
OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (build 11.0.20+8, mixed mode)

We are running Java 11 with only a maxheap of -Xmx10g and  this logging option:  -Xlog:gc*,safepoint=info:file=/Users/foo/gc11_%p_%t.log:time,uptimemillis:filecount=5,filesize=200m

I am attaching the report.
[report.txt.gz](https://github.com/mgm3746/garbagecat/files/12793957/report.txt.gz)

**Comment by mgm3746** [comment]
The release is very old. The best way to run is with docker(podman), that way you always get the latest build:
$ docker run --pull=always -v "$PWD":/home/garbagecat/files:z ghcr.io/mgm3746/garbagecat:main --console /home/garbagecat/files/src/test/gc-example.log > report.txt

**Comment by mgm3746** [comment]
Please re-open and attach the complete gc logging file, if there is still an issue in the latest code.
