### ISSUE TITLE
Java 21 and ZGC

### ISSUE THREAD

**Issue by Lu5ck** [mgm3746/garbagecat#199]
Commandline
`java -jar garbagecat-4.0.2-SNAPSHOT.jar -p -c nzgc.log > result.txt`

[nzgc.log](https://github.com/mgm3746/garbagecat/files/13828547/nzgc.log)
[result.txt](https://github.com/mgm3746/garbagecat/files/13828548/result.txt)

**Comment by mgm3746** [comment]
Thank you for reporting this. I will take a look.

**Comment by mgm3746** [comment]
I have accounted for these patterns. Please test the latest code, and let me know if you find any other issues.

**Comment by mgm3746** [comment]
I'm assuming this resolved your issue. If not, please re-open this or another issue.
