### ISSUE TITLE
1000 UNIDENTIFIED LOG LINE(S) - cannot parse lines with hostname decorator

### ISSUE THREAD

**Issue by osrodka** [mgm3746/garbagecat#204]
Garbagecat cannot handle hostname decorator:
`-Xlog:gc*=debug,safepoint,age*:file=/somepath/gclog.log:hostname,utctime,uptime,level,tags:filecount=10,filesize=1G`

Run with:
`docker run -v "$PWD":/home/garbagecat/files:z garbagecat:latest --console -p -j "-Xms18432m -Xmx18432m -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:+ParallelRefProcEnabled -XX:+PreserveFramePointer -XX:+UseG1GC -XX:+UseNUMA -XX:+UseStringDeduplication -XX:-AlwaysPreTouch -XX:CodeCacheExpansionSize=1048576 -XX:CompileThreshold=3000 -XX:ErrorFile=/somepath/hs_err_pid%p.log -XX:HeapDumpPath=/somepath -XX:InitialCodeCacheSize=512m -XX:ReservedCodeCacheSize=1024m" /home/garbagecat/files/gclog_with_hostname_decorator.log > report.out`

[report.zip](https://github.com/mgm3746/garbagecat/files/14209686/report.zip)
[gclog_with_hostname_decorator.zip](https://github.com/mgm3746/garbagecat/files/14209689/gclog_with_hostname_decorator.zip)

**Comment by mgm3746** [comment]
What is your use case for including the hostname in each logging line? I'm assuming you are running in a container environment where you have many JVMs running and sending gc logging to some logging aggregator, and you are using the hostname to identify the logging in the mixed logging? Is that correct?

**Comment by mgm3746** [comment]
This is now in the latest container build. Please test and confirm.

**Comment by mgm3746** [comment]
If you find any issues with the implementation, please re-open.
