### ISSUE TITLE
Docker image for Linux arm64

### ISSUE THREAD

**Issue by harry-xm** [mgm3746/garbagecat#205]
On arm64 Linux, I can not run garbagecat in Docker:

```
Unable to find image 'ghcr.io/mgm3746/garbagecat:main' locally
main: Pulling from mgm3746/garbagecat
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

This can be fixed by pushing [multi-platform images](https://docs.docker.com/build/building/multi-platform/) to the registry.

**Comment by mgm3746** [comment]
Thank you, I will take a look.

**Comment by mgm3746** [comment]
Hi,

I believe I have added what is needed here:
https://github.com/mgm3746/garbagecat/blob/main/.github/workflows/docker-publish.yml

It seems to have built the arm/64 image:
https://github.com/mgm3746/garbagecat/pkgs/container/garbagecat

Please test and confirm.

Thank you,
Mike

**Comment by mgm3746** [comment]
I believe this is fixed. If not, please re-open.
