### ISSUE TITLE
Request for some info on what is/is not supported in G1 collector

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mgm3746/garbagecat#34]
```
I would really like to use this tool or a tool like it to analyze G1 collector 
data.

There seems to be some G1 code in here, but its not clear what level of G1 
support works.

Info around this would be useful.

Thanks,

Scott



```

Original issue reported on code.google.com by `skellic...@gmail.com` on 20 May 2013 at 11:52

**Comment by mgm3746** [comment]
The G1 collector is now fully supported. Best results are obtained using the following standard recommended logging options:
-XX:+PrintGC -Xloggc:gc.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime
