### ISSUE TITLE
Output filename argument

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#53]
Please add command line argument for specifying the output filename. For example:

```
# garbagecat --output myreport.txt gc.log
# garbagecat -o myreport.txt gc.log
```

**Comment by mgm3746** [comment]
Complete (note that previous usage of 'o' is now '-j' / '--javaoptions'): https://github.com/mgm3746/garbagecat/commit/168603cde73d97307672eee6c530ad5bc24d0bb7
