### ISSUE TITLE
Compare system memory and configured heap size

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#58]
The following is pulled from a GC log:

````
Java HotSpot(TM) 64-Bit Server VM (25.111-b14) for linux-amd64 JRE (1.8.0_111-b14), built on Sep 22 2016 16:14:03 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
Memory: 4k page, physical 1922156k(1275984k free), swap 2097148k(1954136k free)
CommandLine flags: -XX:InitialHeapSize=1366294528 -XX:MaxHeapSize=4718592000 -XX:+PrintGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC 
````

Note the `Memory: 4k page, physical 1922156k(1275984k free)` and the heap is configured to use ~4.7G . This means the heap would most certainly start utilizing swap memory which could be detrimental to performance. 

Can garbagecat be configured to check for this and provide a suggestion in the analysis output to increase RAM on the system?

**Comment by mgm3746** [comment]
https://github.com/mgm3746/garbagecat/commit/d075178a679bc0b334bf3ace036deb7411b7bdc9
