### ISSUE TITLE
Categorize analysis output suggestions

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#59]
Some suggestions provided by garbagecat are more significant for performance concerns than others. For example, `A significant amount of stopped time (>20%) is not GC related` would be more important than `Add -XX:+HeapDumpOnOutOfMemoryError. This option does not impact performance`. 

Can the suggestions be categorized or ranked in some way so quickly finding the most relevant suggestions is easier?

**Comment by mgm3746** [comment]
https://github.com/mgm3746/garbagecat/commit/bfc249fcddca9a43b273ac5d55eabf6715b2dd49
