### ISSUE TITLE
ExplicitGCInvokesConcurrent suggestion for G1

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#84]
```
# garbagecat -p backupgc.log.current.20170329_2232.gz 
# grep -A2 '^error' report.txt 
error
----------------------------------------
*Add -XX:+ExplicitGCInvokesConcurrent so explicit garbage collection is handled concurrently by the CMS and G1 collectors. Or if not making remote method calls and not exporting remote objects like EJBs (everything runs in the same JVM), disable explicit garbage collection altogether with -XX:+DisableExplicitGC.
```

There were no explicit GC calls in the log file that was analyzed. The suggestion is in the error section which leads me to believe my GC log was affected. 

The suggestion is still valid, however, since there are not actually any explicit GC calls, I think the suggestion would be better suited in info section.

Complete GC log attached.
[gc.txt](https://github.com/mgm3746/garbagecat/files/882407/gc.txt)

**Comment by mgm3746** [comment]
Split the analysis into 2, one error when explicit gc is found, one more an error level jvm option recommendation.
