### ISSUE TITLE
gc_stats.log analysis 

### ISSUE THREAD

**Issue by Dvikasred** [mgm3746/garbagecat#90]
Index Super InstBytes KlassBytes annotations    CpAll MethodCount Bytecodes MethodAll    ROAll     RWAll     Total ClassName
19999    53         0        520         120      496           3        16       456      416      1336      1752 com.splwg.rts.webservices.SYNCPLAN
20000 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20001 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20002 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20003 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20004 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20005 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20006 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20007 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20008 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20009 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20010 75294         0        592           0      456           3        28       536      376      1376      1752 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20011 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20012 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20013 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20014 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20015 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20016 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20017 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20018 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20019 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20020 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20021 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20022 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20023 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20024 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20025 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20026 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20027 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20028 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20029 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20030 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20031 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20032 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20033 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20034 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20035 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20036 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20037 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20038 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20039 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20040 75294         0        592           0      376           3        28       536      376      1296      1672 com.splwg.rts.webservices.SYNCPLAN$JaxbAccessorF_syncplandata
20041    53         0        520         120      496           3        16       456      416      1336      1752 com.splwg.rts.webservices.TIGHTENBOND

**Comment by mgm3746** [comment]
Hi, this looks like jcmd GC.class_stats output. garbage only analyzes gc logging created with the -verbose:gc option.
