### ISSUE TITLE
There are unidentified lines for young GC when it triggered as Metadata GC Threshold

### ISSUE THREAD

**Issue by durgeshanaokar** [mgm3746/garbagecat#92]
[gc.txt](https://github.com/mgm3746/garbagecat/files/967375/gc.txt)
The garbage cat is not able to read lines when young GC triggered with Metadata GC Threshold.

~~~~~
20.748: [GC (Metadata GC Threshold)  288163K->251266K(1253376K), 0.0183041 secs]
70.789: [GC (Metadata GC Threshold)  821896K->714225K(1245696K), 0.0573330 secs]
~~~~~

**Comment by mgm3746** [comment]
This trigger has been added to VERBOSE_GC_YOUNG. Thank you for reporting this.

**Comment by mgm3746** [comment]
Should not be fixed in latest.
