### ISSUE TITLE
Unidentified log line(s)

### ISSUE THREAD

**Issue by leiyu97** [mgm3746/garbagecat#94]
70232.705: [Full GC (Ergonomics)  746358K->339626K(932352K), 0.7798887 secs]
73833.489: [GC (System.gc())  548585K->547005K(932352K), 0.0152219 secs]
73833.505: [Full GC (System.gc())  547005K->198385K(932352K), 1.5687705 secs]

Does this indicates System.gc() is called directly in the code?

**Comment by mgm3746** [comment]
Yes, the application code called System.gc(), or the JVM calls it for Distributed Garbage Collection.
