### ISSUE TITLE
Way to determine if you are using the latest build

### ISSUE THREAD

**Issue by mgm3746** [mgm3746/garbagecat#99]
*Add latest build to report version header?
*Add to -v --version output?
*Add new flag to check if latest version (e.g. -l --latest)?

**Comment by bostrt** [comment]
See https://github.com/mgm3746/garbagecat/pull/102

**Comment by mgm3746** [comment]
Reporting version and latest version is now optional. Examples:

1) $ java -jar garbagecat-2.0.11-SNAPSHOT.jar -v
Running garbagecat version: 2.0.11-SNAPSHOT

2) $ java -jar garbagecat-2.0.11-SNAPSHOT.jar --version
Running garbagecat version: 2.0.11-SNAPSHOT

3) $ java -jar garbagecat-2.0.11-SNAPSHOT.jar -l
Latest garbagecat version/tag: v2.0.10

4) $ java -jar garbagecat-2.0.11-SNAPSHOT.jar --latest
Latest garbagecat version/tag: v2.0.10

5) $ java -jar garbagecat-2.0.11-SNAPSHOT.jar -v -l
Running garbagecat version: 2.0.11-SNAPSHOT
Latest garbagecat version/tag: v2.0.10

6) $ java -jar garbagecat-2.0.11-SNAPSHOT.jar -v -l gc.log

report.txt:

========================================
Running garbagecat version: 2.0.11-SNAPSHOT
Latest garbagecat version/tag: v2.0.10
========================================
...
